"""放射科英汉术语对照表 - 核心词（解剖+征象）
================================================================================
精简版，直接供医学白名单和引擎使用。
"""
from __future__ import annotations

# ===== 解剖部位 =====
ANATOMY_EN_ZH = {
    # 胸部
    "lung": "肺", "lungs": "双肺", "left lung": "左肺", "right lung": "右肺",
    "upper lobe": "上叶", "left upper lobe": "左上叶", "right upper lobe": "右上叶",
    "lower lobe": "下叶", "left lower lobe": "左下叶", "right lower lobe": "右下叶",
    "middle lobe": "中叶", "lingula": "舌段",
    "lung apex": "肺尖", "lung base": "肺底",
    "lung parenchyma": "肺实质", "pulmonary parenchyma": "肺实质",
    "lung hilum": "肺门", "hilar": "肺门的",
    "left hilum": "左肺门", "right hilum": "右肺门",
    "pleura": "胸膜", "pleural": "胸膜的",
    "mediastinum": "纵隔", "mediastinal": "纵隔的",
    "anterior mediastinum": "前纵隔", "middle mediastinum": "中纵隔",
    "posterior mediastinum": "后纵隔",
    "chest wall": "胸壁",
    "rib": "肋骨", "ribs": "肋骨",
    "sternum": "胸骨",
    "thorax": "胸部", "thoracic": "胸廓的",
    "trachea": "气管", "main bronchus": "主支气管",
    "bronchus": "支气管", "bronchial": "支气管的",
    "carina": "隆突",
    "pulmonary artery": "肺动脉", "pulmonary vein": "肺静脉",
    "aorta": "主动脉", "ascending aorta": "升主动脉",
    "descending aorta": "降主动脉", "aortic arch": "主动脉弓",
    "superior vena cava": "上腔静脉", "inferior vena cava": "下腔静脉",
    "heart": "心脏", "cardiac": "心脏的",
    "left atrium": "左心房", "right atrium": "右心房",
    "left ventricle": "左心室", "right ventricle": "右心室",
    "pericardium": "心包", "pericardial": "心包的",
    "esophagus": "食管", "oesophagus": "食管", "esophageal": "食管的",
    "thymus": "胸腺",
    "lymph node": "淋巴结",
    "hilar lymph node": "肺门淋巴结",
    "mediastinal lymph node": "纵隔淋巴结",
    "subcarinal lymph node": "隆突下淋巴结",
    "paratracheal lymph node": "气管旁淋巴结",
    "axillary lymph node": "腋窝淋巴结",
    "supraclavicular lymph node": "锁骨上淋巴结",
    "diaphragm": "膈肌",
    "costophrenic angle": "肋膈角",
    "pleural space": "胸膜腔",
    "pneumothorax": "气胸",

    # 头部
    "brain": "脑", "cerebrum": "大脑", "cerebellum": "小脑", "brainstem": "脑干",
    "cerebral hemisphere": "大脑半球",
    "left cerebral hemisphere": "左侧大脑半球",
    "right cerebral hemisphere": "右侧大脑半球",
    "frontal lobe": "额叶", "parietal lobe": "顶叶",
    "temporal lobe": "颞叶", "occipital lobe": "枕叶",
    "left frontal lobe": "左侧额叶", "right frontal lobe": "右侧额叶",
    "left temporal lobe": "左侧颞叶", "right temporal lobe": "右侧颞叶",
    "left parietal lobe": "左侧顶叶", "right parietal lobe": "右侧顶叶",
    "left occipital lobe": "左侧枕叶", "right occipital lobe": "右侧枕叶",
    "basal ganglia": "基底节", "basal ganglion": "基底节",
    "thalamus": "丘脑", "corpus callosum": "胼胝体",
    "internal capsule": "内囊", "external capsule": "外囊",
    "lateral ventricle": "侧脑室",
    "third ventricle": "第三脑室", "fourth ventricle": "第四脑室",
    "skull": "颅骨", "cranial": "颅骨的", "intracranial": "颅内",
    "paranasal sinus": "鼻旁窦", "paranasal sinuses": "鼻旁窦",
    "maxillary sinus": "上颌窦", "ethmoid sinus": "筛窦",
    "sphenoid sinus": "蝶窦", "frontal sinus": "额窦",
    "orbit": "眼眶", "orbital": "眼眶的", "globe": "眼球",
    "optic nerve": "视神经", "temporal bone": "颞骨",
    "mastoid": "乳突", "internal auditory canal": "内听道",
    "cerebellopontine angle": "桥小脑角",
    "suprasellar cistern": "鞍上池",
    "cerebral sulcus": "脑沟", "cerebral gyrus": "脑回",
    "cerebral cortex": "大脑皮层", "white matter": "白质", "gray matter": "灰质",
    "subarachnoid space": "蛛网膜下腔",
    "subdural space": "硬膜下腔", "epidural space": "硬膜外腔",

    # 脊柱
    "cervical spine": "颈椎", "cervical vertebrae": "颈椎",
    "thoracic spine": "胸椎", "thoracic vertebrae": "胸椎",
    "lumbar spine": "腰椎", "lumbar vertebrae": "腰椎",
    "sacrum": "骶骨", "coccyx": "尾骨",
    "intervertebral disc": "椎间盘",
    "spinal canal": "椎管", "spinal cord": "脊髓",
    "neural foramen": "椎间孔",

    # 腹部
    "liver": "肝脏", "hepatic": "肝脏的",
    "left hepatic lobe": "肝左叶", "right hepatic lobe": "肝右叶",
    "gallbladder": "胆囊", "pancreas": "胰腺", "pancreatic": "胰腺的",
    "spleen": "脾脏", "splenic": "脾脏的",
    "kidney": "肾脏", "kidneys": "双肾",
    "left kidney": "左肾", "right kidney": "右肾", "renal": "肾的",
    "adrenal gland": "肾上腺",
    "stomach": "胃", "gastric": "胃的",
    "small bowel": "小肠", "large bowel": "大肠",
    "colon": "结肠",
    "ascending colon": "升结肠", "transverse colon": "横结肠",
    "descending colon": "降结肠", "sigmoid colon": "乙状结肠",
    "rectum": "直肠", "appendix": "阑尾",
    "peritoneum": "腹膜", "retroperitoneum": "腹膜后",

    # 盆腔
    "bladder": "膀胱", "prostate": "前列腺",
    "uterus": "子宫", "ovary": "卵巢",
    "pelvis": "盆腔", "pelvic": "盆腔的",

    # 肌肉骨骼
    "bone": "骨骼", "bones": "骨骼",
    "cortical bone": "骨皮质", "bone marrow": "骨髓",
    "joint": "关节", "shoulder joint": "肩关节", "hip joint": "髋关节",
    "knee joint": "膝关节",
    "anterior cruciate ligament": "前交叉韧带",
    "posterior cruciate ligament": "后交叉韧带",
    "meniscus": "半月板",
    "medial meniscus": "内侧半月板", "lateral meniscus": "外侧半月板",
    "rotator cuff": "肩袖",
    "tendon": "肌腱", "ligament": "韧带", "muscle": "肌肉",
    "soft tissue": "软组织", "subcutaneous tissue": "皮下组织",
}

# ===== 影像征象 =====
FINDING_EN_ZH = {
    # 密度/信号
    "opacity": "密度增高", "opacification": "密度增高",
    "consolidation": "实变",
    "ground-glass opacity": "磨玻璃影", "ground glass opacity": "磨玻璃影",
    "GGO": "磨玻璃影",
    "nodule": "结节", "nodules": "结节",
    "mass": "肿块", "masses": "肿块",
    "lesion": "病灶", "lesions": "病灶",
    "infiltrate": "浸润", "infiltration": "浸润",
    "reticulation": "网状影", "reticular": "网状的",
    "fibrosis": "纤维化", "scar": "瘢痕", "scarring": "瘢痕形成",
    "atelectasis": "肺不张", "collapse": "肺不张/塌陷",
    "hyperinflation": "肺过度充气",
    "hypolucency": "透亮度减低",
    "hypodensity": "密度减低", "hyperdensity": "密度增高",
    "isodensity": "等密度",
    "hypoattenuation": "低密度", "hyperattenuation": "高密度",
    "hypointensity": "低信号", "hyperintensity": "高信号",
    "isointensity": "等信号",
    "T1 hyperintensity": "T1高信号", "T2 hyperintensity": "T2高信号",
    "T1 hypointensity": "T1低信号", "T2 hypointensity": "T2低信号",
    "FLAIR hyperintensity": "FLAIR高信号",
    "enhancement": "强化", "enhanced": "强化",
    "calcification": "钙化", "cavity": "空洞", "cavitation": "空洞形成",
    "bullae": "肺大疱", "bulla": "肺大疱",
    "cyst": "囊肿", "cysts": "囊肿",
    "bronchiectasis": "支气管扩张",
    "pleural thickening": "胸膜增厚",
    "effusion": "积液",
    "edema": "水肿",
    "cardiogenic edema": "心源性肺水肿",
    "thrombus": "血栓", "thrombosis": "血栓形成",
    "embolism": "栓塞", "pulmonary embolism": "肺栓塞", "PE": "肺栓塞",
    "aortic dissection": "主动脉夹层",
    "aneurysm": "动脉瘤",
    "stenosis": "狭窄", "stricture": "狭窄", "narrowing": "狭窄",
    "dilatation": "扩张", "dilation": "扩张",
    "atherosclerosis": "动脉粥样硬化", "plaque": "斑块",
    "pericardial effusion": "心包积液",
    "ascites": "腹水", "hydronephrosis": "肾积水",

    # 肿瘤/病变
    "neoplasm": "肿瘤", "neoplasms": "肿瘤", "tumor": "肿瘤",
    "benign": "良性", "malignant": "恶性",
    "primary malignancy": "原发恶性肿瘤",
    "metastasis": "转移", "metastases": "转移瘤", "metastatic": "转移性的",
    "lymphadenopathy": "淋巴结病",
    "enlarged lymph node": "淋巴结增大",
    "lymph node metastasis": "淋巴结转移",
    "local invasion": "局部侵犯",
    "metastatic disease": "转移性病变",
    "benign neoplasm": "良性肿瘤", "malignant neoplasm": "恶性肿瘤",
    "primary lung cancer": "原发性肺癌",
    "lung adenocarcinoma": "肺腺癌",
    "adenocarcinoma": "腺癌",
    "squamous cell carcinoma": "鳞状细胞癌",
    "small cell carcinoma": "小细胞癌",
    "non-small cell lung cancer": "非小细胞肺癌",
    "NSCLC": "非小细胞肺癌",
    "SCLC": "小细胞肺癌",
    "hepatocellular carcinoma": "肝细胞癌",
    "renal cell carcinoma": "肾细胞癌",
    "glioma": "胶质瘤", "meningioma": "脑膜瘤",
    "glioblastoma": "胶质母细胞瘤",
    "hemangioma": "血管瘤", "lipoma": "脂肪瘤",
    "lymphoma": "淋巴瘤",
    "Hodgkin lymphoma": "霍奇金淋巴瘤",
    "non-Hodgkin lymphoma": "非霍奇金淋巴瘤",
    "myeloma": "骨髓瘤", "multiple myeloma": "多发性骨髓瘤",
    "hematoma": "血肿", "contusion": "挫伤",
    "hemorrhage": "出血", "hemorrhagic": "出血性的",
    "ischemia": "缺血", "infarct": "梗死", "infarction": "梗死",
    "acute infarct": "急性梗死", "chronic infarct": "慢性梗死",
    "congenital anomaly": "先天性异常",
    "herniated disc": "椎间盘突出",
    "disc herniation": "椎间盘突出",
    "spinal stenosis": "椎管狭窄",
    "mass effect": "占位效应", "midline shift": "中线移位",

    # 骨折
    "fracture": "骨折", "fractures": "骨折",
    "compression fracture": "压缩性骨折",
    "degenerative change": "退行性改变", "degenerative": "退行性的",
    "osteoarthritis": "骨关节炎", "osteoporosis": "骨质疏松",
    "osteopenia": "骨量减少",
}

# ===== 检查技术 =====
MODALITY_EN_ZH = {
    "CT": "CT", "computed tomography": "计算机断层扫描",
    "HRCT": "高分辨率CT", "high resolution CT": "高分辨率CT",
    "MRI": "磁共振", "magnetic resonance imaging": "磁共振成像",
    "MR": "磁共振",
    "PET": "PET", "positron emission tomography": "正电子发射断层显像",
    "PET-CT": "PET-CT",
    "SPECT": "单光子发射计算机断层显像",
    "ultrasound": "超声", "sonography": "超声检查",
    "X-ray": "X线", "radiograph": "X线片",
    "chest X-ray": "胸部X线", "CXR": "胸部X线",
    "fluoroscopy": "透视",
    # 序列
    "T1WI": "T1加权", "T2WI": "T2加权",
    "T1 weighted": "T1加权", "T2 weighted": "T2加权",
    "FLAIR": "FLAIR序列",
    "STIR": "短时反转恢复序列",
    "DWI": "DWI", "ADC": "ADC图",
    "SWI": "磁敏感加权成像",
    # 增强/相位
    "contrast-enhanced": "增强", "post-contrast": "增强后",
    "non-contrast": "平扫", "plain scan": "平扫",
    "arterial phase": "动脉期", "portal venous phase": "门脉期",
    "delayed phase": "延迟期",
    # 术语
    "attenuation": "密度", "signal intensity": "信号强度",
    "window width": "窗宽", "window level": "窗位",
    "slice thickness": "层厚",
    "reconstruction": "重建",
    "MPR": "多平面重建",
    "MIP": "最大密度投影",
    "VR": "容积再现",
}

# ===== 疾病/诊断 =====
DISEASE_EN_ZH = {
    "pneumonia": "肺炎", "tuberculosis": "结核",
    "active tuberculosis": "活动性结核", "old tuberculosis": "陈旧结核",
    "tuberculoma": "结核球", "miliary tuberculosis": "粟粒性结核",
    "COPD": "慢性阻塞性肺疾病",
    "chronic obstructive pulmonary disease": "慢性阻塞性肺疾病",
    "asthma": "哮喘", "pulmonary fibrosis": "肺纤维化",
    "IPF": "特发性肺纤维化",
    "pulmonary hypertension": "肺动脉高压",
    "sarcoidosis": "结节病",
    "lung adenocarcinoma": "肺腺癌",
    "glioblastoma": "胶质母细胞瘤",
    "pituitary adenoma": "垂体腺瘤",
    "acoustic neuroma": "听神经瘤",
    "craniopharyngioma": "颅咽管瘤",
    "chordoma": "脊索瘤",
    "Moyamoya disease": "烟雾病",
    "aortic dissection": "主动脉夹层",
    "AAA": "腹主动脉瘤",
    "abdominal aortic aneurysm": "腹主动脉瘤",
}

# ===== 结论/程度/建议 =====
CONCLUSION_EN_ZH = {
    "consider": "考虑", "suggestive of": "提示", "consistent with": "符合",
    "compatible with": "符合", "favor": "倾向",
    "recommend": "建议", "suggest": "建议",
    "follow-up": "随访", "follow up": "随访", "followup": "随访",
    "interval change": "间期变化",
    "stable": "稳定", "unchanged": "无变化",
    "worsening": "进展", "improved": "好转",
    "resolved": "已吸收", "partially resolved": "部分吸收",
    "new": "新发", "increasing": "增大", "decreasing": "缩小",
    "surveillance": "监测", "recurrence": "复发", "remission": "缓解",
    "prognosis": "预后", "staging": "分期", "TNM staging": "TNM分期",
    "early stage": "早期", "advanced stage": "晚期",
    "locally advanced": "局部晚期",
    "complete response": "完全缓解", "CR": "完全缓解",
    "partial response": "部分缓解", "PR": "部分缓解",
    "stable disease": "疾病稳定", "SD": "疾病稳定",
    "progressive disease": "疾病进展", "PD": "疾病进展",
    "complication": "并发症",
    "postoperative": "术后", "preoperative": "术前",
    "adjuvant": "辅助的", "neoadjuvant": "新辅助的",
    "palliative": "姑息性的", "curative": "根治性的",
}

# 合并所有来源
ALL_TERMS = {}
ALL_TERMS.update(ANATOMY_EN_ZH)
ALL_TERMS.update(FINDING_EN_ZH)
ALL_TERMS.update(MODALITY_EN_ZH)
ALL_TERMS.update(DISEASE_EN_ZH)
ALL_TERMS.update(CONCLUSION_EN_ZH)
